#mongo with 3 collection
version: "3"

services:
  toxiproxy:
    container_name: toxiproxy
    image: shopify/toxiproxy
    ports:
      - 8474:8474
      - 27019:27019
  toxiproxy-config:
    image: "shopify/toxiproxy"
    entrypoint: >
      sh -c "/go/bin/toxiproxy-cli -h toxiproxy:8474 create mongo --listen 0.0.0.0:27019 --upstream mongo:27017"
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

